"""empty message

Revision ID: ead4efb1ac79
Revises: 25ae0d0578f9
Create Date: 2023-07-10 18:26:12.380084

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ead4efb1ac79'
down_revision = '25ae0d0578f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=mysql.VARCHAR(length=100),
               comment='用户名',
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=mysql.VARCHAR(length=100),
               comment=None,
               existing_comment='用户名',
               existing_nullable=False)

    # ### end Alembic commands ###
